replicaCount: 1
namespace: faluwi-dev

release:
  name: test-node
  
image:
  repository: docker.io/faluwi/test:v1.9
  pullPolicy: IfNotPresent

imagePullSecret:
  name: private-registry

container:
  name: nodeapp
  port: 3000

service:
  type: ClusterIP
  protocol: TCP
  port: 80
  targetPort: 3000

route:
  path: /
