replicaCount: 1
namespace: faluwi-dev

release:
  name: test-node
  
image:
  repository: docker.io/faluwi/test:v1.7
  pullPolicy: IfNotPresent

imagePullSecret:
  name: private-registry

container:
  port: 3000

service:
  protocol: TCP
  port: 4000
  targetPort: 3000

route:
  path: \
  
