kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-node
  namespace: faluwi-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: test
          image: faluwi/test:v1.2
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
