apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.release.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.release.name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.container.port }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
