apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node
  template:
    metadata:
      labels:
        app: test-node
    spec:
      containers:
      - name: nodeapp
        image: faluwi/test:v1.6
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: private-registry
