apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.release.name }}-route
  namespace: {{ .Values.namespace }}
spec:
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ .Values.release.name }}-service
  port:
    targetPort: {{ .Values.service.port }}
