apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .release.name }}-route
  namespace: {{ .namespace }}
spec:
  path: {{ .route.path }}
  to:
    kind: Service
    name: {{ .release.name }}-service
  port:
    targetPort: {{ .service.port }}
