apiVersion: v1
kind: Service
metadata:
  name: {{ .release.name }}-service
  namespace: {{ .namespace }}
spec:
  selector:
    app: {{ .release.name }}
  ports:
    - protocol: {{ .service.protocol }}
      port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
