apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.release.name }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
