apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: hello-world
  name: hello-world
spec:
  output:
    to:
      kind: DockerImage
      name: "docker.io/faluwi/test:v1.5"
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Binary
    binary: {}
    secrets:
    - secret:
        name: private-registry
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: Dockerfile
