kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/faluwi/NodeJSApp"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkins/Jenkinsfile
